# ---------------- Exports -------------------
export PS1="\\$ \$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/ ') \W > \[$(tput sgr0)\]"
export PATH="${PATH}:${HOME}/.cargo/bin"
export MANPAGER="less"
export EDITOR="lvim"
# ---------------- Source --------------------
. ~/.aliasrc
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
# --------------- Config ---------------------
stty ixon
